<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/downloadvar/app/modules/Widgets/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2013-07-08T04:06:41+0000

return array (
  'downloadvarWidgetsBaseAction' => 'C:\\workspace\\downloadvar\\app/modules/Widgets/lib/action/downloadvarWidgetsBaseAction.class.php',
  'downloadvarWidgetsBaseModel' => 'C:\\workspace\\downloadvar\\app/modules/Widgets/lib/model/downloadvarWidgetsBaseModel.class.php',
  'downloadvarWidgetsBaseView' => 'C:\\workspace\\downloadvar\\app/modules/Widgets/lib/view/downloadvarWidgetsBaseView.class.php',
);

?>