<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/downloadvar/app/modules/News/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2013-07-08T04:06:40+0000

return array (
  'downloadvarNewsBaseAction' => 'C:\\workspace\\downloadvar\\app/modules/News/lib/action/downloadvarNewsBaseAction.class.php',
  'downloadvarNewsBaseModel' => 'C:\\workspace\\downloadvar\\app/modules/News/lib/model/downloadvarNewsBaseModel.class.php',
  'downloadvarNewsBaseView' => 'C:\\workspace\\downloadvar\\app/modules/News/lib/view/downloadvarNewsBaseView.class.php',
);

?>