<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/downloadvar/app/modules/News/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2013-07-08T04:06:40+0000

return array (
)

?>