<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/workspace/downloadvar/app/modules/News/validate/Matter/Admin/Index.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2013-07-08T04:06:40+0000



?>